### PR TITLE
Cache the web3 provider

### LINKED ISSUE #27: Logged out when refreshing the page
Log out when Refresh error. To reproduce it:

- I’m in the id mgr
- I REFRESH the page (or cmd+R)
- I get “logged out” (not a full logout, but you are redirected to the login page)

### PR DESCRIPTION
**Pull request by jessgusclark**
## Refreshing the page
Allows a user to refresh the page and rLogin will remember the provider and will automatically log back in. 

Resolves #27 

## Listeners

In addition, it also implements the missing EIP 1193 listeners, `accountsChanged`, `chainChanged`, and `disconnect` (which is emitted by WC, not metamask). This allows the user to change to a different identity quickly. One thing to note with the DataVault and Metamask, when switching networks, the popup to sign the message for the DV is behind the accounts screen. The user will need to click the notification to see and sign the message.

EIP 1139 listeners are in the <Authenticated /> component because it is the most stable way to interact with React context. I tried placing these listeners in the `login()` function, but `Context` gets mutated and is not longer a single point of truth. Interacting directly with the context from a component is best practice.

## DV Screen Component cleanup

Finally, it shows a message no the `<DataVaultComponent />` screen if the datavault is not saved into context. This shouldn't happen, but it cleaned up the functions below it. It removed `context.dvClient && ` from each as the dvClient is now a guarentee.

### CODE REVIEW

File: src/app/DataVault/DataVaultComponent.tsx [hunk 1]
```diff
@@ -23,16 +23,22 @@ const DataVaultComponent: React.FC<DataVaultComponentProps> = ({
...
-  const handleSwap = (key: string, content: string, id: string) =>
-    context.dvClient && swapValue(context.dvClient, key, content, id)
-  const handleDownload = () => context.dvClient && downloadBackup(context.dvClient)
-  const handleGetKeyContent = (key: string) =>
-    context.dvClient && getKeyContent(context.dvClient, key)
+  if (!dvClient) {
+    return (
+      <div className="content data-vault">
+        <h2>Could not connect to the DataVault</h2>
+        <p>Your wallet may be asking for permission.</p>
```
Comment (ilanolkies) [inline src/app/DataVault/DataVaultComponent.tsx:32]: Should we add a _retry_ button? Maybe user clicked on cancel or some other strange behaviour. What do you think? We can do it in another PR anyway

**Review by ilanolkies — APPROVED** [review]
LRGTM!

File: src/app/DataVault/DataVaultComponent.tsx (hunk 1 above)
Comment (jessgusclark) [reply src/app/DataVault/DataVaultComponent.tsx:32]: Yes, it would be a good idea to have a retry button for the DV. I added ticket #58 for this.
